In [281]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier


import warnings
warnings.filterwarnings("ignore")


In [282]:
# Read the CSV file
df = pd.read_csv('preprocessed_CRR.csv')

In [283]:
# creating numerical and categorical dataframes
cat_cols = [col for col in df.columns if df[col].dtype == 'O']
cat_cols


['hotel',
 'arrival_date_month',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status_date']

In [284]:
cat_df = df[cat_cols]
cat_df.head()

hotel arrival_date_month meal market_segment distribution_channel  \
0  Resort Hotel               July   BB         Direct               Direct   
1  Resort Hotel               July   BB         Direct               Direct   
2  Resort Hotel               July   BB         Direct               Direct   
3  Resort Hotel               July   BB      Corporate            Corporate   
4  Resort Hotel               July   BB      Online TA                TA/TO   

  reserved_room_type deposit_type customer_type reservation_status_date  
0                  C   No Deposit     Transient              2015-07-01  
1                  C   No Deposit     Transient              2015-07-01  
2                  A   No Deposit     Transient              2015-07-02  
3                  A   No Deposit     Transient              2015-07-02  
4                  A   No Deposit     Transient              2015-07-03

In [285]:
cat_df['reservation_status_date'] = pd.to_datetime(cat_df['reservation_status_date'])

cat_df['year'] = cat_df['reservation_status_date'].dt.year
cat_df['month'] = cat_df['reservation_status_date'].dt.month
cat_df['day'] = cat_df['reservation_status_date'].dt.day

In [286]:

cat_df.drop(['reservation_status_date','arrival_date_month'] , axis = 1, inplace = True)
cat_df.head()

hotel meal market_segment distribution_channel reserved_room_type  \
0  Resort Hotel   BB         Direct               Direct                  C   
1  Resort Hotel   BB         Direct               Direct                  C   
2  Resort Hotel   BB         Direct               Direct                  A   
3  Resort Hotel   BB      Corporate            Corporate                  A   
4  Resort Hotel   BB      Online TA                TA/TO                  A   

  deposit_type customer_type  year  month  day  
0   No Deposit     Transient  2015      7    1  
1   No Deposit     Transient  2015      7    1  
2   No Deposit     Transient  2015      7    2  
3   No Deposit     Transient  2015      7    2  
4   No Deposit     Transient  2015      7    3

In [287]:
# encoding categorical variables

cat_df['hotel'] = cat_df['hotel'].map({'Resort Hotel' : 0, 'City Hotel' : 1})

cat_df['meal'] = cat_df['meal'].map({'BB' : 0, 'FB': 1, 'HB': 2, 'SC': 3, 'Undefined': 4})

cat_df['market_segment'] = cat_df['market_segment'].map({'Direct': 0, 'Corporate': 1, 'Online TA': 2, 'Offline TA/TO': 3,
                                                           'Complementary': 4, 'Groups': 5, 'Undefined': 6, 'Aviation': 7})

cat_df['distribution_channel'] = cat_df['distribution_channel'].map({'Direct': 0, 'Corporate': 1, 'TA/TO': 2, 'Undefined': 3,
                                                                       'GDS': 4})

cat_df['reserved_room_type'] = cat_df['reserved_room_type'].map({'C': 0, 'A': 1, 'D': 2, 'E': 3, 'G': 4, 'F': 5, 'H': 6,
                                                                   'L': 7, 'B': 8})

cat_df['deposit_type'] = cat_df['deposit_type'].map({'No Deposit': 0, 'Refundable': 1, 'Non Refund': 3})

cat_df['customer_type'] = cat_df['customer_type'].map({'Transient': 0, 'Contract': 1, 'Transient-Party': 2, 'Group': 3})

cat_df['year'] = cat_df['year'].map({2015: 0, 2014: 1, 2016: 2, 2017: 3})

cat_df.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
0      0     0               0                     0                   0   
1      0     0               0                     0                   0   
2      0     0               0                     0                   1   
3      0     0               1                     1                   1   
4      0     0               2                     2                   1   

   deposit_type  customer_type  year  month  day  
0             0              0     0      7    1  
1             0              0     0      7    1  
2             0              0     0      7    2  
3             0              0     0      7    2  
4             0              0     0      7    3

In [288]:
num_df = df.drop(columns = cat_cols, axis = 1)
num_df.drop('is_canceled', axis = 1, inplace = True)
num_df

lead_time  arrival_date_week_number  arrival_date_day_of_month  \
0             342                        27                          1   
1             737                        27                          1   
2               7                        27                          1   
3              13                        27                          1   
4              14                        27                          1   
...           ...                       ...                        ...   
119205         23                        35                         30   
119206        102                        35                         31   
119207         34                        35                         31   
119208        109                        35                         31   
119209        205                        35                         29   

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
0                             0                     0       2       0.0   
1                             0                     0       2       0.0   
2                             0                     1       1       0.0   
3                             0                     1       1       0.0   
4                             0                     2       2       0.0   
...                         ...                   ...     ...       ...   
119205                        2                     5       2       0.0   
119206                        2                     5       3       0.0   
119207                        2                     5       2       0.0   
119208                        2                     5       2       0.0   
119209                        2                     7       2       0.0   

        babies  is_repeated_guest  previous_cancellations  \
0            0                  0                       0   
1            0                  0                       0   
2            0                  0                       0   
3            0                  0                       0   
4            0                  0                       0   
...        ...                ...                     ...   
119205       0                  0                       0   
119206       0                  0                       0   
119207       0                  0                       0   
119208       0                  0                       0   
119209       0                  0                       0   

        previous_bookings_not_canceled  agent  company     adr  \
0                                    0    0.0      0.0    0.00   
1                                    0    0.0      0.0    0.00   
2                                    0    0.0      0.0   75.00   
3                                    0  304.0      0.0   75.00   
4                                    0  240.0      0.0   98.00   
...                                ...    ...      ...     ...   
119205                               0  394.0      0.0   96.14   
119206                               0    9.0      0.0  225.43   
119207                               0    9.0      0.0  157.71   
119208                               0   89.0      0.0  104.40   
119209                               0    9.0      0.0  151.20   

        required_car_parking_spaces  total_of_special_requests  
0                                 0                          0  
1                                 0                          0  
2                                 0                          0  
3                                 0                          0  
4                                 0                          1  
...                             ...                        ...  
119205                            0                          0  
119206                            0                          2  
119207                            0                          4  
119208                            0       

In [289]:
num_df.var()


lead_time                         11422.361808
arrival_date_week_number            184.990111
arrival_date_day_of_month            77.107192
stays_in_weekend_nights               0.990258
stays_in_week_nights                  3.599010
adults                                0.330838
children                              0.159070
babies                                0.009508
is_repeated_guest                     0.030507
previous_cancellations                0.713887
previous_bookings_not_canceled        2.244415
agent                             11485.169679
company                            2897.684308
adr                                2543.589039
required_car_parking_spaces           0.060201
total_of_special_requests             0.628652
dtype: float64

In [290]:
# normalizing numerical variables

num_df['lead_time'] = np.log(num_df['lead_time'] + 1)
num_df['arrival_date_week_number'] = np.log(num_df['arrival_date_week_number'] + 1)
num_df['arrival_date_day_of_month'] = np.log(num_df['arrival_date_day_of_month'] + 1)
num_df['agent'] = np.log(num_df['agent'] + 1)
num_df['company'] = np.log(num_df['company'] + 1)
num_df['adr'] = np.log(num_df['adr'] + 1)


num_df.var()


lead_time                         2.582757
arrival_date_week_number          0.440884
arrival_date_day_of_month         0.506325
stays_in_weekend_nights           0.990258
stays_in_week_nights              3.599010
adults                            0.330838
children                          0.159070
babies                            0.009508
is_repeated_guest                 0.030507
previous_cancellations            0.713887
previous_bookings_not_canceled    2.244415
agent                             3.535793
company                           1.346883
adr                               0.515480
required_car_parking_spaces       0.060201
total_of_special_requests         0.628652
dtype: float64

In [291]:
num_df['adr'] = num_df['adr'].fillna(value = num_df['adr'].mean())

num_df.head()

lead_time  arrival_date_week_number  arrival_date_day_of_month  \
0   5.837730                  3.332205                   0.693147   
1   6.603944                  3.332205                   0.693147   
2   2.079442                  3.332205                   0.693147   
3   2.639057                  3.332205                   0.693147   
4   2.708050                  3.332205                   0.693147   

   stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
0                        0                     0       2       0.0       0   
1                        0                     0       2       0.0       0   
2                        0                     1       1       0.0       0   
3                        0                     1       1       0.0       0   
4                        0                     2       2       0.0       0   

   is_repeated_guest  previous_cancellations  previous_bookings_not_canceled  \
0                  0                       0                               0   
1                  0                       0                               0   
2                  0                       0                               0   
3                  0                       0                               0   
4                  0                       0                               0   

      agent  company       adr  required_car_parking_spaces  \
0  0.000000      0.0  0.000000                            0   
1  0.000000      0.0  0.000000                            0   
2  0.000000      0.0  4.330733                            0   
3  5.720312      0.0  4.330733                            0   
4  5.484797      0.0  4.595120                            0   

   total_of_special_requests  
0                          0  
1                          0  
2                          0  
3                          0  
4                          1

In [292]:
X = pd.concat([cat_df, num_df], axis = 1)
y = df['is_canceled']

X.shape, y.shape


((119210, 26), (119210,))

In [293]:
# splitting data into training set and test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)


In [294]:
X_train.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
75373      1     0               5                     2                   1   
2352       0     2               2                     2                   2   
66307      1     0               2                     2                   2   
13583      0     0               2                     2                   3   
82962      1     3               2                     2                   1   

       deposit_type  customer_type  year  month  day  ...  children  babies  \
75373             3              2     0      7    2  ...       0.0       0   
2352              0              0     0     10   12  ...       0.0       0   
66307             0              0     2     12   13  ...       0.0       0   
13583             0              0     3      7   27  ...       0.0       0   
82962             0              0     2      1   15  ...       0.0       0   

       is_repeated_guest  previous_cancellations  \
75373                  0                       1   
2352                   0                       0   
66307                  0                       0   
13583                  0                       0   
82962                  0                       0   

       previous_bookings_not_canceled     agent  company       adr  \
75373                               0  0.693147      0.0  4.143135   
2352                                0  5.484797      0.0  4.629863   
66307                               0  2.302585      0.0  4.879007   
13583                               0  5.484797      0.0  5.602119   
82962                               0  2.397895      0.0  4.215086   

       required_car_parking_spaces  total_of_special_requests  
75373                            0                          0  
2352                             0                          2  
66307                            0                          0  
13583                            0                          3  
82962                            0                          0  

[5 rows x 26 columns]

In [295]:
X_test.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
78692      1     0               3                     2                   1   
3478       0     1               5                     0                   1   
87576      1     0               7                     1                   2   
23989      0     0               1                     1                   1   
73556      1     0               2                     2                   3   

       deposit_type  customer_type  year  month  day  ...  children  babies  \
78692             0              2     0     10   16  ...       0.0       0   
3478              3              0     0     11    9  ...       0.0       0   
87576             0              2     2      5    6  ...       0.0       0   
23989             0              2     2      5   10  ...       0.0       0   
73556             0              0     3      8   17  ...       0.0       0   

       is_repeated_guest  previous_cancellations  \
78692                  0                       0   
3478                   0                       0   
87576                  1                       1   
23989                  0                       0   
73556                  0                       0   

       previous_bookings_not_canceled     agent   company       adr  \
78692                               0  4.605170  0.000000  4.615121   
3478                                0  0.000000  0.000000  4.394449   
87576                               1  5.036953  0.000000  4.709530   
23989                               0  0.000000  4.912655  3.761200   
73556                               0  2.302585  0.000000  5.411646   

       required_car_parking_spaces  total_of_special_requests  
78692                            0                          0  
3478                             0                          0  
87576                            0                          0  
23989                            0                          0  
73556                            0                          0  

[5 rows x 26 columns]

In [296]:
y_train.head(), y_test.head()

(75373    1
 2352     0
 66307    1
 13583    1
 82962    0
 Name: is_canceled, dtype: int64,
 78692    0
 3478     1
 87576    1
 23989    0
 73556    1
 Name: is_canceled, dtype: int64)

In [297]:
#logistic Regression

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)
conf = confusion_matrix(y_test, y_pred_lr)
clf_report = classification_report(y_test, y_pred_lr)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.8128512708665381
Confusion Matrix : 
[[21389  1219]
 [ 5474  7681]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.80      0.95      0.86     22608
           1       0.86      0.58      0.70     13155

    accuracy                           0.81     35763
   macro avg       0.83      0.76      0.78     35763
weighted avg       0.82      0.81      0.80     35763



In [298]:
#KNN

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

acc_knn = accuracy_score(y_test, y_pred_knn)
conf = confusion_matrix(y_test, y_pred_knn)
clf_report = classification_report(y_test, y_pred_knn)

print(f"Accuracy Score of KNN is : {acc_knn}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of KNN is : 0.8933814277325728
Confusion Matrix : 
[[21815   793]
 [ 3020 10135]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.88      0.96      0.92     22608
           1       0.93      0.77      0.84     13155

    accuracy                           0.89     35763
   macro avg       0.90      0.87      0.88     35763
weighted avg       0.90      0.89      0.89     35763



In [299]:
#Decision Tree Classifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

y_pred_dtc = dtc.predict(X_test)

acc_dtc = accuracy_score(y_test, y_pred_dtc)
conf = confusion_matrix(y_test, y_pred_dtc)
clf_report = classification_report(y_test, y_pred_dtc)

print(f"Accuracy Score of Decision Tree is : {acc_dtc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Decision Tree is : 0.9506752789195537
Confusion Matrix : 
[[21715   893]
 [  871 12284]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.96      0.96      0.96     22608
           1       0.93      0.93      0.93     13155

    accuracy                           0.95     35763
   macro avg       0.95      0.95      0.95     35763
weighted avg       0.95      0.95      0.95     35763



In [300]:
#Random Forest Classifier
rd_clf = RandomForestClassifier()
rd_clf.fit(X_train, y_train)

y_pred_rd_clf = rd_clf.predict(X_test)

acc_rd_clf = accuracy_score(y_test, y_pred_rd_clf)
conf = confusion_matrix(y_test, y_pred_rd_clf)
clf_report = classification_report(y_test, y_pred_rd_clf)

print(f"Accuracy Score of Random Forest is : {acc_rd_clf}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Random Forest is : 0.955288985823337
Confusion Matrix : 
[[22433   175]
 [ 1424 11731]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.94      0.99      0.97     22608
           1       0.99      0.89      0.94     13155

    accuracy                           0.96     35763
   macro avg       0.96      0.94      0.95     35763
weighted avg       0.96      0.96      0.95     35763



In [301]:

etc = ExtraTreesClassifier()
etc.fit(X_train, y_train)

y_pred_etc = etc.predict(X_test)

acc_etc = accuracy_score(y_test, y_pred_etc)
conf = confusion_matrix(y_test, y_pred_etc)
clf_report = classification_report(y_test, y_pred_etc)

print(f"Accuracy Score of Ada Boost Classifier is : {acc_etc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Ada Boost Classifier is : 0.9547017867628554
Confusion Matrix : 
[[22397   211]
 [ 1409 11746]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.94      0.99      0.97     22608
           1       0.98      0.89      0.94     13155

    accuracy                           0.95     35763
   macro avg       0.96      0.94      0.95     35763
weighted avg       0.96      0.95      0.95     35763



In [ ]:
# Models Comparison

models = pd.DataFrame({
    'Model' : ['Logistic Regression', 'KNN', 'Decision Tree Classifier', 'Random Forest Classifier','Extra Trees Classifier'],
    'Score' : [acc_lr, acc_knn, acc_dtc, acc_rd_clf, acc_etc]
})


models.sort_values(by = 'Score', ascending = False)
