In [302]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier


import warnings
warnings.filterwarnings("ignore")


In [303]:
# Read the CSV file
df = pd.read_csv('preprocessed_CRR.csv')

In [304]:
# creating numerical and categorical dataframes
cat_cols = [col for col in df.columns if df[col].dtype == 'O']
cat_cols


['hotel',
 'arrival_date_month',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status_date']

In [305]:
cat_df = df[cat_cols]
cat_df.head()

hotel arrival_date_month meal market_segment distribution_channel  \
0  Resort Hotel               July   BB         Direct               Direct   
1  Resort Hotel               July   BB         Direct               Direct   
2  Resort Hotel               July   BB         Direct               Direct   
3  Resort Hotel               July   BB      Corporate            Corporate   
4  Resort Hotel               July   BB      Online TA                TA/TO   

  reserved_room_type deposit_type customer_type reservation_status_date  
0                  C   No Deposit     Transient              2015-07-01  
1                  C   No Deposit     Transient              2015-07-01  
2                  A   No Deposit     Transient              2015-07-02  
3                  A   No Deposit     Transient              2015-07-02  
4                  A   No Deposit     Transient              2015-07-03

In [306]:
cat_df['reservation_status_date'] = pd.to_datetime(cat_df['reservation_status_date'])

cat_df['year'] = cat_df['reservation_status_date'].dt.year
cat_df['month'] = cat_df['reservation_status_date'].dt.month
cat_df['day'] = cat_df['reservation_status_date'].dt.day

In [307]:

cat_df.drop(['reservation_status_date','arrival_date_month'] , axis = 1, inplace = True)
cat_df.head()

hotel meal market_segment distribution_channel reserved_room_type  \
0  Resort Hotel   BB         Direct               Direct                  C   
1  Resort Hotel   BB         Direct               Direct                  C   
2  Resort Hotel   BB         Direct               Direct                  A   
3  Resort Hotel   BB      Corporate            Corporate                  A   
4  Resort Hotel   BB      Online TA                TA/TO                  A   

  deposit_type customer_type  year  month  day  
0   No Deposit     Transient  2015      7    1  
1   No Deposit     Transient  2015      7    1  
2   No Deposit     Transient  2015      7    2  
3   No Deposit     Transient  2015      7    2  
4   No Deposit     Transient  2015      7    3

In [308]:
# encoding categorical variables

cat_df['hotel'] = cat_df['hotel'].map({'Resort Hotel' : 0, 'City Hotel' : 1})

cat_df['meal'] = cat_df['meal'].map({'BB' : 0, 'FB': 1, 'HB': 2, 'SC': 3, 'Undefined': 4})

cat_df['market_segment'] = cat_df['market_segment'].map({'Direct': 0, 'Corporate': 1, 'Online TA': 2, 'Offline TA/TO': 3,
                                                           'Complementary': 4, 'Groups': 5, 'Undefined': 6, 'Aviation': 7})

cat_df['distribution_channel'] = cat_df['distribution_channel'].map({'Direct': 0, 'Corporate': 1, 'TA/TO': 2, 'Undefined': 3,
                                                                       'GDS': 4})

cat_df['reserved_room_type'] = cat_df['reserved_room_type'].map({'C': 0, 'A': 1, 'D': 2, 'E': 3, 'G': 4, 'F': 5, 'H': 6,
                                                                   'L': 7, 'B': 8})

cat_df['deposit_type'] = cat_df['deposit_type'].map({'No Deposit': 0, 'Refundable': 1, 'Non Refund': 3})

cat_df['customer_type'] = cat_df['customer_type'].map({'Transient': 0, 'Contract': 1, 'Transient-Party': 2, 'Group': 3})

cat_df['year'] = cat_df['year'].map({2015: 0, 2014: 1, 2016: 2, 2017: 3})

cat_df.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
0      0     0               0                     0                   0   
1      0     0               0                     0                   0   
2      0     0               0                     0                   1   
3      0     0               1                     1                   1   
4      0     0               2                     2                   1   

   deposit_type  customer_type  year  month  day  
0             0              0     0      7    1  
1             0              0     0      7    1  
2             0              0     0      7    2  
3             0              0     0      7    2  
4             0              0     0      7    3

In [309]:
num_df = df.drop(columns = cat_cols, axis = 1)
num_df.drop('is_canceled', axis = 1, inplace = True)
num_df

lead_time  arrival_date_week_number  arrival_date_day_of_month  \
0             342                        27                          1   
1             737                        27                          1   
2               7                        27                          1   
3              13                        27                          1   
4              14                        27                          1   
...           ...                       ...                        ...   
119205         23                        35                         30   
119206        102                        35                         31   
119207         34                        35                         31   
119208        109                        35                         31   
119209        205                        35                         29   

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
0                             0                     0       2       0.0   
1                             0                     0       2       0.0   
2                             0                     1       1       0.0   
3                             0                     1       1       0.0   
4                             0                     2       2       0.0   
...                         ...                   ...     ...       ...   
119205                        2                     5       2       0.0   
119206                        2                     5       3       0.0   
119207                        2                     5       2       0.0   
119208                        2                     5       2       0.0   
119209                        2                     7       2       0.0   

        babies  is_repeated_guest  previous_cancellations  \
0            0                  0                       0   
1            0                  0                       0   
2            0                  0                       0   
3            0                  0                       0   
4            0                  0                       0   
...        ...                ...                     ...   
119205       0                  0                       0   
119206       0                  0                       0   
119207       0                  0                       0   
119208       0                  0                       0   
119209       0                  0                       0   

        previous_bookings_not_canceled  agent  company     adr  \
0                                    0    0.0      0.0    0.00   
1                                    0    0.0      0.0    0.00   
2                                    0    0.0      0.0   75.00   
3                                    0  304.0      0.0   75.00   
4                                    0  240.0      0.0   98.00   
...                                ...    ...      ...     ...   
119205                               0  394.0      0.0   96.14   
119206                               0    9.0      0.0  225.43   
119207                               0    9.0      0.0  157.71   
119208                               0   89.0      0.0  104.40   
119209                               0    9.0      0.0  151.20   

        required_car_parking_spaces  total_of_special_requests  
0                                 0                          0  
1                                 0                          0  
2                                 0                          0  
3                                 0                          0  
4                                 0                          1  
...                             ...                        ...  
119205                            0                          0  
119206                            0                          2  
119207                            0                          4  
119208                            0       

In [310]:
num_df.var()


lead_time                         11422.361808
arrival_date_week_number            184.990111
arrival_date_day_of_month            77.107192
stays_in_weekend_nights               0.990258
stays_in_week_nights                  3.599010
adults                                0.330838
children                              0.159070
babies                                0.009508
is_repeated_guest                     0.030507
previous_cancellations                0.713887
previous_bookings_not_canceled        2.244415
agent                             11485.169679
company                            2897.684308
adr                                2543.589039
required_car_parking_spaces           0.060201
total_of_special_requests             0.628652
dtype: float64

In [311]:
# normalizing numerical variables

num_df['lead_time'] = np.log(num_df['lead_time'] + 1)
num_df['arrival_date_week_number'] = np.log(num_df['arrival_date_week_number'] + 1)
num_df['arrival_date_day_of_month'] = np.log(num_df['arrival_date_day_of_month'] + 1)
num_df['agent'] = np.log(num_df['agent'] + 1)
num_df['company'] = np.log(num_df['company'] + 1)
num_df['adr'] = np.log(num_df['adr'] + 1)


num_df.var()


lead_time                         2.582757
arrival_date_week_number          0.440884
arrival_date_day_of_month         0.506325
stays_in_weekend_nights           0.990258
stays_in_week_nights              3.599010
adults                            0.330838
children                          0.159070
babies                            0.009508
is_repeated_guest                 0.030507
previous_cancellations            0.713887
previous_bookings_not_canceled    2.244415
agent                             3.535793
company                           1.346883
adr                               0.515480
required_car_parking_spaces       0.060201
total_of_special_requests         0.628652
dtype: float64

In [312]:
num_df['adr'] = num_df['adr'].fillna(value = num_df['adr'].mean())

num_df.head()

lead_time  arrival_date_week_number  arrival_date_day_of_month  \
0   5.837730                  3.332205                   0.693147   
1   6.603944                  3.332205                   0.693147   
2   2.079442                  3.332205                   0.693147   
3   2.639057                  3.332205                   0.693147   
4   2.708050                  3.332205                   0.693147   

   stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
0                        0                     0       2       0.0       0   
1                        0                     0       2       0.0       0   
2                        0                     1       1       0.0       0   
3                        0                     1       1       0.0       0   
4                        0                     2       2       0.0       0   

   is_repeated_guest  previous_cancellations  previous_bookings_not_canceled  \
0                  0                       0                               0   
1                  0                       0                               0   
2                  0                       0                               0   
3                  0                       0                               0   
4                  0                       0                               0   

      agent  company       adr  required_car_parking_spaces  \
0  0.000000      0.0  0.000000                            0   
1  0.000000      0.0  0.000000                            0   
2  0.000000      0.0  4.330733                            0   
3  5.720312      0.0  4.330733                            0   
4  5.484797      0.0  4.595120                            0   

   total_of_special_requests  
0                          0  
1                          0  
2                          0  
3                          0  
4                          1

In [313]:
X = pd.concat([cat_df, num_df], axis = 1)
y = df['is_canceled']

X.shape, y.shape


((119210, 26), (119210,))

In [314]:
# splitting data into training set and test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)


In [315]:
X_train.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
71424       1     0               5                     2                   1   
63026       1     0               2                     2                   1   
110829      1     0               3                     2                   1   
22774       0     0               3                     2                   2   
77052       1     0               3                     2                   1   

        deposit_type  customer_type  year  month  day  ...  children  babies  \
71424              3              0     3      5   11  ...       0.0       0   
63026              0              0     2     12    5  ...       0.0       0   
110829             0              0     3      5    5  ...       0.0       0   
22774              0              0     2      4    6  ...       0.0       0   
77052              0              2     0      9    7  ...       0.0       0   

        is_repeated_guest  previous_cancellations  \
71424                   0                       0   
63026                   0                       0   
110829                  0                       0   
22774                   0                       0   
77052                   0                       0   

        previous_bookings_not_canceled     agent  company       adr  \
71424                                0  4.477337      0.0  4.948760   
63026                                0  2.302585      0.0  4.493121   
110829                               0  3.367296      0.0  4.454347   
22774                                0  5.147494      0.0  3.974058   
77052                                0  1.386294      0.0  4.352469   

        required_car_parking_spaces  total_of_special_requests  
71424                             0                          0  
63026                             0                          1  
110829                            0                          0  
22774                             0                          0  
77052                             0                          0  

[5 rows x 26 columns]

In [316]:
X_test.head()

hotel  meal  market_segment  distribution_channel  reserved_room_type  \
39218      0     0               0                     0                   2   
43601      1     0               3                     2                   1   
7362       0     0               3                     2                   2   
67450      1     3               2                     2                   1   
71856      1     3               2                     2                   1   

       deposit_type  customer_type  year  month  day  ...  children  babies  \
39218             0              2     3      8   12  ...       0.0       0   
43601             0              2     0      9   23  ...       0.0       0   
7362              0              0     2      4   28  ...       0.0       0   
67450             0              0     2     11    6  ...       0.0       0   
71856             0              0     3      6   20  ...       0.0       0   

       is_repeated_guest  previous_cancellations  \
39218                  0                       0   
43601                  0                       0   
7362                   0                       0   
67450                  0                       0   
71856                  0                       0   

       previous_bookings_not_canceled     agent  company       adr  \
39218                               0  5.525453      0.0  5.501258   
43601                               0  3.044522      0.0  4.189655   
7362                                0  5.501258      0.0  5.225747   
67450                               0  2.302585      0.0  4.605170   
71856                               0  2.302585      0.0  4.875197   

       required_car_parking_spaces  total_of_special_requests  
39218                            1                          1  
43601                            0                          0  
7362                             0                          0  
67450                            0                          1  
71856                            0                          1  

[5 rows x 26 columns]

In [317]:
y_train.head(), y_test.head()

(71424     1
 63026     1
 110829    0
 22774     0
 77052     0
 Name: is_canceled, dtype: int64,
 39218    0
 43601    0
 7362     1
 67450    1
 71856    1
 Name: is_canceled, dtype: int64)

In [318]:
#logistic Regression

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)
conf = confusion_matrix(y_test, y_pred_lr)
clf_report = classification_report(y_test, y_pred_lr)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.8107541313648184
Confusion Matrix : 
[[21312  1133]
 [ 5635  7683]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.79      0.95      0.86     22445
           1       0.87      0.58      0.69     13318

    accuracy                           0.81     35763
   macro avg       0.83      0.76      0.78     35763
weighted avg       0.82      0.81      0.80     35763



In [319]:
#KNN

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

acc_knn = accuracy_score(y_test, y_pred_knn)
conf = confusion_matrix(y_test, y_pred_knn)
clf_report = classification_report(y_test, y_pred_knn)

print(f"Accuracy Score of KNN is : {acc_knn}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of KNN is : 0.89173167799122
Confusion Matrix : 
[[21657   788]
 [ 3084 10234]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.88      0.96      0.92     22445
           1       0.93      0.77      0.84     13318

    accuracy                           0.89     35763
   macro avg       0.90      0.87      0.88     35763
weighted avg       0.90      0.89      0.89     35763



In [320]:
#Decision Tree Classifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

y_pred_dtc = dtc.predict(X_test)

acc_dtc = accuracy_score(y_test, y_pred_dtc)
conf = confusion_matrix(y_test, y_pred_dtc)
clf_report = classification_report(y_test, y_pred_dtc)

print(f"Accuracy Score of Decision Tree is : {acc_dtc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Decision Tree is : 0.9500041942790034
Confusion Matrix : 
[[21586   859]
 [  929 12389]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.96      0.96      0.96     22445
           1       0.94      0.93      0.93     13318

    accuracy                           0.95     35763
   macro avg       0.95      0.95      0.95     35763
weighted avg       0.95      0.95      0.95     35763



In [321]:
#Random Forest Classifier
rd_clf = RandomForestClassifier()
rd_clf.fit(X_train, y_train)

y_pred_rd_clf = rd_clf.predict(X_test)

acc_rd_clf = accuracy_score(y_test, y_pred_rd_clf)
conf = confusion_matrix(y_test, y_pred_rd_clf)
clf_report = classification_report(y_test, y_pred_rd_clf)

print(f"Accuracy Score of Random Forest is : {acc_rd_clf}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Random Forest is : 0.9535833123619383
Confusion Matrix : 
[[22255   190]
 [ 1470 11848]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.94      0.99      0.96     22445
           1       0.98      0.89      0.93     13318

    accuracy                           0.95     35763
   macro avg       0.96      0.94      0.95     35763
weighted avg       0.96      0.95      0.95     35763



In [322]:

etc = ExtraTreesClassifier()
etc.fit(X_train, y_train)

y_pred_etc = etc.predict(X_test)

acc_etc = accuracy_score(y_test, y_pred_etc)
conf = confusion_matrix(y_test, y_pred_etc)
clf_report = classification_report(y_test, y_pred_etc)

print(f"Accuracy Score of Ada Boost Classifier is : {acc_etc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Ada Boost Classifier is : 0.94978049939882
Confusion Matrix : 
[[22209   236]
 [ 1560 11758]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     22445
           1       0.98      0.88      0.93     13318

    accuracy                           0.95     35763
   macro avg       0.96      0.94      0.95     35763
weighted avg       0.95      0.95      0.95     35763



In [323]:
# Models Comparison

models = pd.DataFrame({
    'Model' : ['Logistic Regression', 'KNN', 'Decision Tree Classifier', 'Random Forest Classifier','Extra Trees Classifier'],
    'Score' : [acc_lr, acc_knn, acc_dtc, acc_rd_clf, acc_etc]
})


models.sort_values(by = 'Score', ascending = False)


Model     Score
3  Random Forest Classifier  0.953583
2  Decision Tree Classifier  0.950004
4    Extra Trees Classifier  0.949780
1                       KNN  0.891732
0       Logistic Regression  0.810754